create table if not exists public.medicamentos (
  id bigint generated by default as identity primary key,
  nome text not null,
  laboratorio text,
  validade date not null,
  indicacao text,
  contraindicacoes text,
  posologia text,
  efeitos_adversos text,
  precaucoes text,
  observacoes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.medicamentos enable row level security;

-- Para um projeto acadêmico sem autenticação, estas políticas permitem o CRUD público.
-- Em produção, substitua por políticas vinculadas a auth.uid().
create policy "vida_public_select" on public.medicamentos for select using (true);
create policy "vida_public_insert" on public.medicamentos for insert with check (true);
create policy "vida_public_update" on public.medicamentos for update using (true);
create policy "vida_public_delete" on public.medicamentos for delete using (true);
