create table if not exists public.medicamentos (
  id bigint generated by default as identity primary key,
  sync_id text not null unique,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  nome text not null,
  laboratorio text not null default '',
  validade date not null,
  indicacao text not null default '',
  contraindicacoes text not null default '',
  posologia text not null default '',
  efeitos_adversos text not null default '',
  precaucoes text not null default '',
  observacoes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Migração segura para instalações criadas por versões anteriores.
alter table public.medicamentos add column if not exists sync_id text;
alter table public.medicamentos add column if not exists user_id uuid default auth.uid() references auth.users(id) on delete cascade;
create unique index if not exists medicamentos_sync_id_idx on public.medicamentos(sync_id);

alter table public.medicamentos enable row level security;

drop policy if exists "vida_public_select" on public.medicamentos;
drop policy if exists "vida_public_insert" on public.medicamentos;
drop policy if exists "vida_public_update" on public.medicamentos;
drop policy if exists "vida_public_delete" on public.medicamentos;
drop policy if exists "vida_user_select" on public.medicamentos;
drop policy if exists "vida_user_insert" on public.medicamentos;
drop policy if exists "vida_user_update" on public.medicamentos;
drop policy if exists "vida_user_delete" on public.medicamentos;

create policy "vida_user_select" on public.medicamentos
  for select to authenticated using (auth.uid() = user_id);
create policy "vida_user_insert" on public.medicamentos
  for insert to authenticated with check (auth.uid() = user_id);
create policy "vida_user_update" on public.medicamentos
  for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "vida_user_delete" on public.medicamentos
  for delete to authenticated using (auth.uid() = user_id);
